### ISSUE TITLE
inport error

### ISSUE THREAD

**Issue by TigerHH6866** [Tencent/LightDiffusionFlow#10]
fn_import_workflow /tmp/gradio/b93478f7d7fad911c5cb4ef45961a93dc6c8b52e/ipadapter0.6-768hirefix1.2.flow
Reusing loaded model 摄影-Photon_v1.safetensors [ec41bd2a82] to load 摄影-墨幽人造人_v1040精简.safetensors [ea8e801c3a]
Loading weights [ea8e801c3a] from /root/autodl-tmp/stable-diffusion-webui/models/Stable-diffusion/摄影-墨幽人造人_v1040精简.safetensors
Applying attention optimization: xformers... done.
Weights loaded in 2.2s (send model to cpu: 0.9s, load weights from disk: 0.7s, apply weights to model: 0.1s, move model to device: 0.3s).
Traceback (most recent call last):
  File "/root/miniconda3/lib/python3.10/site-packages/gradio/routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "/root/miniconda3/lib/python3.10/site-packages/gradio/blocks.py", line 1431, in process_api
    result = await self.call_function(
  File "/root/miniconda3/lib/python3.10/site-packages/gradio/blocks.py", line 1103, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/root/miniconda3/lib/python3.10/site-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/root/miniconda3/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/root/miniconda3/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "/root/miniconda3/lib/python3.10/site-packages/gradio/utils.py", line 707, in wrapper
    response = f(*args, **kwargs)
  File "/root/autodl-tmp/stable-diffusion-webui/extensions/LightDiffusionFlow/scripts/state_api.py", line 137, in set_dropdowns
    res = re.search(r"(\[[0-9A-Fa-f]{8,10}\])", new_value)
  File "/root/miniconda3/lib/python3.10/re.py", line 200, in search
    return _compile(pattern, flags).search(string)
TypeError: expected string or bytes-like object
[ipadapter0.6-768hirefix1.2.flow.zip](https://github.com/Tencent/LightDiffusionFlow/files/12794678/ipadapter0.6-768hirefix1.2.flow.zip)

**Comment by TigerHH6866** [comment]
more info
webui 1.6.0
ControlNet v1.1.410

**Comment by LegionFu** [comment]
我更新到跟你一样的版本，然后导入你提供的flow文件，测试好像没有问题？你这个报错也挺奇怪的，你把插件更新到最新的版本再试试？

**Comment by TigerHH6866** [comment]
都是最新版本，目前依然出现该错误

云端3090
