### ISSUE TITLE
ModuleNotFoundError: No module named 'scripts.lightdiffusionflow_config'

### ISSUE THREAD

**Issue by jason571** [Tencent/LightDiffusionFlow#24]
当scripts目录下有多个py模块文件时，python文件会提示下面错误，怎么解决这个问题，试了各种方法不行。
包括增加sys.path.appent(''),
使用__init__.py可以临时解决，但是如果其他插件也是在scripts目录有多个问题，第一个使用的有效，其他的就不能使用
*** Error loading script: state_api.py
    Traceback (most recent call last):
      File "/mnt/p/home/flyang/stable-diffusion-webui/modules/scripts.py", line 381, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "/mnt/p/home/flyang/stable-diffusion-webui/modules/script_loading.py", line 12, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "/mnt/p/home/flyang/stable-diffusion-webui/extensions/LightDiffusionFlow/scripts/state_api.py", line 26, in <module>
        from scripts import lightdiffusionflow_version, lightdiffusionflow_config
    ImportError: cannot import name 'lightdiffusionflow_version' from 'scripts' (/home/flyang/.local/lib/python3.10/site-packages/scripts/__init__.py)

---
*** Error loading script: state_settings.py
    Traceback (most recent call last):
      File "/mnt/p/home/flyang/stable-diffusion-webui/modules/scripts.py", line 381, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "/mnt/p/home/flyang/stable-diffusion-webui/modules/script_loading.py", line 12, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "/mnt/p/home/flyang/stable-diffusion-webui/extensions/LightDiffusionFlow/scripts/state_settings.py", line 4, in <module>
        from scripts.lightdiffusionflow_config import OutputPrompt
    ModuleNotFoundError: No module named 'scripts.lightdiffusionflow_config'

**Comment by LegionFu** [comment]
我其实有点没太懂你是什么情况。你是修改了插件代码然后出现了这个问题？还是直接安装完运行就有这个问题？
正常这个scripts目录在启动加载的时候sd会自动加到环境里，所以代码里直接这样加载应该是没问题的。
或者有可能是你其他装了什么插件之类的出现了冲突？你可以再仔细说一下你具体的情况，方便我们定位问题。

**Comment by LegionFu** [comment]
更新一下代码再试试？今天发现有部分人加载会出现这个错误，所以我修改了一下代码的写法，现在应该没问题了。
